language: node_js
node_js:
- node
install:
- npm ci
script:
- npm run deploy
- rm -rf ./docs/RavindaranNavinn_Resume.pdf && node print.js
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  target_branch: master
  keep_history: true